# Generated by Django 5.2.14 on 2026-06-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='ORDER',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='PRODUCT',
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='ORDER_DETAILS',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='orderDetails',
        ),
        migrations.DeleteModel(
            name='ReturnOrder',
        ),
    ]
