# Generated by Django 5.2.14 on 2026-06-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_orderdetails_returnorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(default='positive', max_length=100),
            preserve_default=False,
        ),
    ]
