# Generated by Django 5.2.14 on 2026-06-29 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_used_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('UsedProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.used_product')),
            ],
        ),
    ]
