# Generated by Django 5.2.14 on 2026-07-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='off',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
