# Generated by Django 5.2.14 on 2026-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_offer_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
