# Generated by Django 5.2.14 on 2026-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
